### ISSUE TITLE
How to change Submit button style?

### ISSUE THREAD

**Issue by ASakkeer** [dgonz64/rhfa-react-native#1]
I'm trying to change rhfa-react-native form styles. I've changed everything except the submit button style. I couldn't find the style properties for the button. Please, If anyone knows that let me know. 

<img width="347" alt="Screenshot 2020-11-07 at 9 39 06 AM" src="https://user-images.githubusercontent.com/56513278/98431666-6b994480-20dd-11eb-90ce-88c0e0fec709.png">

**Comment by dgonz64** [comment]
Hello. Sorry for the delay.

I will take a closer look. At the moment you can provide your own button in two ways:

### stand-alone, completely controlled by you

This is the method the demo uses. You use imperative submit to force a submit on that button's click:

```javascript
    const formRef = useRef()

    function handleImperativeSubmit() {
      formRef.current.submit()
    }

    return (
      <Autoform ref={formRef} {...} />
      <MyButton onClick={handleImperativeSubmit} />
    )
```

### As a child of Autoform

That way you can use a `type="submit"` button and it will trig the submit when pressed.

```javascript
    return (
      <Autoform {...}>
        <MySubmitButton />
      </Autoform>
    )
```

**Comment by ASakkeer** [comment]
> Hello. Sorry for the delay.
> 
> I will take a closer look. At the moment you can provide your own button in two ways:
> 
> ### stand-alone, completely controlled by you
> This is the method the demo uses. You use imperative submit to force a submit on that button's click:
> 
> ```js
>     const formRef = useRef()
> 
>     function handleImperativeSubmit() {
>       formRef.current.submit()
>     }
> 
>     return (
>       <Autoform ref={formRef} {...} />
>       <MyButton onClick={handleImperativeSubmit} />
>     )
> ```
> 
> ### As a child of Autoform
> That way you can use a `type="submit"` button and it will trig the submit when pressed.
> 
> ```js
>     return (
>       <Autoform {...}>
>         <MySubmitButton />
>       </Autoform>
>     )
> ```

Thanks for the reply. I wrote a custom button for this. :)
